/*
 * Smart Display - Main Application
 *
 * Features:
 * - Real-time clock display with server sync
 * - 7-day weather forecast with temperature chart
 * - Screen-based architecture with automatic update management
 *
 * Architecture:
 * - time_manager: Handles time display and syncing (always active)
 * - weather_manager: Handles weather data (only when weather_screen is active)
 * - Screen Management: Automatically starts/stops updates based on active
 * screen
 *
 * Usage:
 *   switchToScreen(SCREEN_WEATHER);  // Load weather screen (starts weather
 * updates) switchToScreen(SCREEN_NONE);     // Unload screen (stops weather
 * updates) getCurrentScreen();              // Get current active screen
 */

#include <Arduino.h>
#include <HTTPClient.h>
#include <WiFi.h>

#include "gt911.h"            // Touch screen operations (GT911)
#include "lvgl_port.h"        // LVGL porting functions
#include "rgb_lcd_port.h"     // Waveshare RGB LCD driver
#include "time_manager.h"     // Time management
#include "ui.h"               // UI (generated by SquareLine Studio)
#include "weather_manager.h"  // Weather management

static const char* TAG = "main";  // Tag for logging

// WiFi credentials
const char* ssid = "BrHomeLan";
const char* password = "20BrHomeSafe20";

static WeatherManager weatherManager;
static TimeManager timeManager;

extern objects_t objects;

// ================== Screen Management ==================

enum Screen {
  SCREEN_NONE,
  SCREEN_WEATHER,
  // Add more screens here:
  // SCREEN_SETTINGS,
  // SCREEN_MENU,
  // SCREEN_PHOTOS,
};

static Screen currentScreen = SCREEN_NONE;

// ================== WiFi Connection ==================

void connectWiFi() {
  Serial.print("Connecting to WiFi");
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("\nWiFi connected!");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

// ================== Setup ==================

void initStartScreen() {
  Serial.println("Initializing start screen...");

  currentScreen = SCREEN_WEATHER;

  if (lvgl_port_lock(-1)) {
    // Initialize UI components (creates and loads the weather screen)
    ui_init();
    timeManager.initTimeManager();
    lvgl_port_unlock();
  }

  Serial.println("Start screen initialized");
}

void setup() {
  // Initialize serial
  Serial.begin(115200);
  delay(1000);
  Serial.println("Smart Display Starting...");

  // Hardware initialization
  static esp_lcd_panel_handle_t panel_handle = NULL;
  static esp_lcd_touch_handle_t tp_handle = NULL;

  // Initialize touch screen controller
  tp_handle = touch_gt911_init();

  // Initialize LCD hardware
  panel_handle = waveshare_esp32_s3_rgb_lcd_init();

  // Initialize LVGL library
  ESP_ERROR_CHECK(lvgl_port_init(panel_handle, tp_handle));
  ESP_LOGI(TAG, "LVGL initialized");

  // Network and services initialization
  connectWiFi();

  initStartScreen();

  Serial.println("Setup complete!");
}

// ================== Main Loop ==================

void loop() {

  if (lvgl_port_lock(-1)) {
    switch (currentScreen) {
      case SCREEN_NONE: {
      } break;
      case SCREEN_WEATHER: {
        timeManager.updateTimeData();
        weatherManager.updateWeatherData();
      } break;
      default:
        break;
    }
    lvgl_port_unlock();
  }

  // Small delay to prevent tight looping
  delay(10);
}
