/*
 * Ported LVGL 8.4 and display the official demo interface.
 */
#include <Arduino.h>
#include "rgb_lcd_port.h" // Header for Waveshare RGB LCD driver
#include "gt911.h"        // Header for touch screen operations (GT911)

#include "lvgl_port.h"      // LVGL porting functions for integration
// #include <demos/lv_demos.h> // LVGL demo headers
#include "ui.h"             // UI header generated by SquareLine Studio

// https://www.youtube.com/nishad2m8
// https://buymeacoffee.com/nishad2m8

static const char *TAG = "main";  // Tag for logging

extern objects_t objects;

void setup()
{
  Serial.begin(115200);
  delay(1000);
  Serial.println("LVGL Demo Start");
  static esp_lcd_panel_handle_t panel_handle = NULL; // Declare a handle for the LCD panel
  static esp_lcd_touch_handle_t tp_handle = NULL;    // Declare a handle for the touch panel

  // Initialize the GT911 touch screen controller
  tp_handle = touch_gt911_init();

  // Initialize the Waveshare ESP32-S3 RGB LCD hardware
  panel_handle = waveshare_esp32_s3_rgb_lcd_init();

  // Turn on the LCD backlight
  //wavesahre_rgb_lcd_bl_on();


  // Initialize LVGL with the panel and touch handles
  ESP_ERROR_CHECK(lvgl_port_init(panel_handle, tp_handle));

  ESP_LOGI(TAG, "Display LVGL demos");

  // Lock the mutex because LVGL APIs are not thread-safe
  if (lvgl_port_lock(-1))
  {
    // Uncomment and run the desired demo functions here
    // lv_demo_stress();  // Stress test demo
    // lv_demo_benchmark(); // Benchmark demo
    // lv_demo_music();     // Music demo
    // lv_demo_widgets();    // Widgets demo
    ui_init();
    // Release the mutex after the demo execution
    lvgl_port_unlock();
  }

  // wifi_sta_init("valorant", "88888888");
}

void loop()
{
  static int counter = 1;
  static unsigned long lastUpdate = 0;

  
  // Update every 1000ms (1 second)
  if (millis() - lastUpdate >= 1000) {
    lastUpdate = millis();
    
    // Just print to serial
    Serial.print("Hello World: ");
    Serial.println(counter);

    // Lock LVGL before modifying UI
    if (lvgl_port_lock(-1)) {
      // Create dynamic text with counter
      char buffer[32];
      snprintf(buffer, sizeof(buffer), "Count: %d", counter);
      
      // Set the header label text using objects.header
      lv_label_set_text(objects.header, buffer);
      
      // Unlock LVGL
      lvgl_port_unlock();
    }
    
    counter++;
  }
}
